#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
#include "../src/core/rt/util/ScheduleCalculator.h"

using json = nlohmann::json;
using namespace mxrc::core::rt::util;

int main(int argc, char** argv) {
    if (argc != 3) {
        std::cerr << "Usage: " << argv[0] << " <config.json> <output.h>\n";
        std::cerr << "Example: " << argv[0] << " config/rt_schedule.json build/generated/RTSchedule.h\n";
        return 1;
    }

    const std::string config_path = argv[1];
    const std::string output_path = argv[2];

    try {
        // JSON 파일 읽기
        std::ifstream config_file(config_path);
        if (!config_file.is_open()) {
            std::cerr << "Error: Cannot open config file: " << config_path << "\n";
            return 1;
        }

        json config;
        config_file >> config;
        config_file.close();

        // periods_ms 배열 추출
        if (!config.contains("periods_ms") || !config["periods_ms"].is_array()) {
            std::cerr << "Error: 'periods_ms' field is missing or not an array\n";
            return 1;
        }

        std::vector<uint32_t> periods_ms = config["periods_ms"].get<std::vector<uint32_t>>();
        if (periods_ms.empty()) {
            std::cerr << "Error: 'periods_ms' array is empty\n";
            return 1;
        }

        // GCD/LCM 계산
        ScheduleParams params = calculate(periods_ms);

        std::cout << "Schedule calculation complete:\n";
        std::cout << "  Minor cycle: " << params.minor_cycle_ms << " ms\n";
        std::cout << "  Major cycle: " << params.major_cycle_ms << " ms\n";
        std::cout << "  Number of slots: " << params.num_slots << "\n";

        // C++ 헤더 파일 생성
        std::ofstream out_file(output_path);
        if (!out_file.is_open()) {
            std::cerr << "Error: Cannot create output file: " << output_path << "\n";
            return 1;
        }

        // 헤더 가드
        out_file << "#pragma once\n\n";
        out_file << "// Auto-generated by schedule_generator from " << config_path << "\n";
        out_file << "// DO NOT EDIT MANUALLY\n\n";
        out_file << "#include <cstdint>\n";
        out_file << "#include <string>\n\n";

        // 네임스페이스
        out_file << "namespace mxrc {\n";
        out_file << "namespace core {\n";
        out_file << "namespace rt {\n";
        out_file << "namespace generated {\n\n";

        // 스케줄 파라미터
        out_file << "// 스케줄 파라미터\n";
        out_file << "constexpr uint32_t MINOR_CYCLE_MS = " << params.minor_cycle_ms << ";\n";
        out_file << "constexpr uint32_t MAJOR_CYCLE_MS = " << params.major_cycle_ms << ";\n";
        out_file << "constexpr uint32_t NUM_SLOTS = " << params.num_slots << ";\n\n";

        // Action 정의
        if (config.contains("actions") && config["actions"].is_array()) {
            out_file << "// Action 스케줄 정의\n";
            out_file << "struct ActionSchedule {\n";
            out_file << "    const char* name;\n";
            out_file << "    uint32_t period_ms;\n";
            out_file << "    uint32_t wcet_us;\n";
            out_file << "    const char* priority;\n";
            out_file << "    const char* description;\n";
            out_file << "};\n\n";

            const auto& actions = config["actions"];
            out_file << "constexpr ActionSchedule ACTIONS[] = {\n";

            for (size_t i = 0; i < actions.size(); ++i) {
                const auto& action = actions[i];
                out_file << "    {\n";
                out_file << "        \"" << action["name"].get<std::string>() << "\",\n";
                out_file << "        " << action["period_ms"].get<uint32_t>() << ",\n";
                out_file << "        " << action["wcet_us"].get<uint32_t>() << ",\n";
                out_file << "        \"" << action["priority"].get<std::string>() << "\",\n";
                out_file << "        \"" << action["description"].get<std::string>() << "\"\n";
                out_file << "    }";
                if (i < actions.size() - 1) {
                    out_file << ",";
                }
                out_file << "\n";
            }

            out_file << "};\n\n";
            out_file << "constexpr size_t NUM_ACTIONS = " << actions.size() << ";\n\n";
        }

        // 네임스페이스 닫기
        out_file << "} // namespace generated\n";
        out_file << "} // namespace rt\n";
        out_file << "} // namespace core\n";
        out_file << "} // namespace mxrc\n";

        out_file.close();
        std::cout << "Generated: " << output_path << "\n";

        return 0;

    } catch (const json::exception& e) {
        std::cerr << "JSON parsing error: " << e.what() << "\n";
        return 1;
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }
}
